const ADD_PRODUCT = 'Cart/ADD_PRODUCT';
const DELETE_PRODUCT = 'Cart/DELETE_PRODUCT';
const CHANGE_COUNT_PRODUCT = 'Cart/CHANGE_COUNT_PRODUCT';
const CLEAR_CART = 'Cart/CLEAR_CART';
const DISPATCH_CART_SUCCESS = 'Cart/DISPATCH_CART_SUCCESS';
const DISPATCH_CART_FAILURE = 'Cart/DISPATCH_CART_FAILURE';
const DISPATCH_CART_STARTED = 'Cart/DISPATCH_CART_STARTED';

export {
	ADD_PRODUCT,
	DELETE_PRODUCT,
	CHANGE_COUNT_PRODUCT,
	CLEAR_CART,
	DISPATCH_CART_SUCCESS,
	DISPATCH_CART_FAILURE,
	DISPATCH_CART_STARTED,
};
