const ADD_GOOD = 'Cart/ADD_GOOD';
const DELETE_GOOD = 'Cart/DELETE_GOOD';
const CHANGE_COUNT_GOOD = 'Cart/CHANGE_COUNT_GOOD';
const CLEAR_CART = 'Cart/CLEAR_CART';
const DISPATCH_CART_SUCCESS = 'Cart/DISPATCH_CART_SUCCESS';
const DISPATCH_CART_FAILURE = 'Cart/DISPATCH_CART_FAILURE';
const DISPATCH_CART_STARTED = 'Cart/DISPATCH_CART_STARTED';

export {
	ADD_GOOD,
	DELETE_GOOD,
	CHANGE_COUNT_GOOD,
	CLEAR_CART,
	DISPATCH_CART_SUCCESS,
	DISPATCH_CART_FAILURE,
	DISPATCH_CART_STARTED,
};
