const CHANGE_MINPRICE = 'FormFilter/CHANGE_MINPRICE';
const CHANGE_MAXPRICE = 'FormFilter/CHANGE_MAXPRICE';
const CHANGE_MINDISCOUNT = 'FormFilter/CHANGE_MINDISCOUNT';
const RESET_FILTERS = 'FormFilter/RESET_FILTERS';
export {CHANGE_MINPRICE, CHANGE_MAXPRICE, CHANGE_MINDISCOUNT, RESET_FILTERS};
