const SET_FILTER_DATA = 'FormFilter/SET_FILTER_DATA';
const CHANGE_MINPRICE = 'FormFilter/CHANGE_MINPRICE';
const CHANGE_MAXPRICE = 'FormFilter/CHANGE_MAXPRICE';
const CHANGE_MINDISCOUNT = 'FormFilter/CHANGE_MINDISCOUNT';
const RESET_FILTERS = 'FormFilter/RESET_FILTERS';
export {SET_FILTER_DATA, CHANGE_MINPRICE, CHANGE_MAXPRICE, CHANGE_MINDISCOUNT, RESET_FILTERS};
